### ISSUE TITLE
Default nio.cfg block_router should be the one that clone signals.

### ISSUE THREAD

**Issue by hansmosh** [nio-blocks/project_template#4]
It's my opinion that the default settings for a project should be the safest ones, not the fastest ones. By changing to the clone signals block router, their will be a small hit to performance but services will not run into issues with services that send signals to multiple blocks.

Before implementing this, make sure the block router does a check to only clone signals when the signal will be going to multiple blocks. With that in place, the services should lose very little in performance with this block router.

**Comment by f1401martin** [comment]
FYI, signals are cloned only when there is more than one receiving block at the other end.

**Comment by hansmosh** [comment]
Great. That's what I thought but I wanted to double check before making this update.

**Comment by hansmosh** [comment]
This has already been fixed by 3ef38d7cce788d473a95e683a7ece00e3f3fded1
